// This file is auto-generated.

pub const Importance = enum {
    hot,
    important,
    default,
};

pub const ElementInfo = struct {
    id: u32,
    name: []const u8,
    importance: Importance,
};

pub const IdInfo = struct {
    id: u32,
    name: []const u8,
};

pub const elements = [_]ElementInfo {
    ElementInfo { .id = 0x1A45DFA3, .name = "EBML", .importance = .default, },
    ElementInfo { .id = 0x4286, .name = "EBMLVersion", .importance = .default, },
    ElementInfo { .id = 0x42F7, .name = "EBMLReadVersion", .importance = .default, },
    ElementInfo { .id = 0x42F2, .name = "EBMLMaxIDLength", .importance = .default, },
    ElementInfo { .id = 0x42F3, .name = "EBMLMaxSizeLength", .importance = .default, },
    ElementInfo { .id = 0x4282, .name = "DocType", .importance = .default, },
    ElementInfo { .id = 0x4287, .name = "DocTypeVersion", .importance = .default, },
    ElementInfo { .id = 0x4285, .name = "DocTypeReadVersion", .importance = .default, },
    ElementInfo { .id = 0x4281, .name = "DocTypeExtension", .importance = .default, },
    ElementInfo { .id = 0x4283, .name = "DocTypeExtensionName", .importance = .default, },
    ElementInfo { .id = 0x4284, .name = "DocTypeExtensionVersion", .importance = .default, },
    ElementInfo { .id = 0xEC, .name = "Void", .importance = .default, },
    ElementInfo { .id = 0xBF, .name = "CRC32", .importance = .default, },
    ElementInfo { .id = 0x18538067, .name = "Segment", .importance = .important, },
    ElementInfo { .id = 0x114D9B74, .name = "SeekHead", .importance = .default, },
    ElementInfo { .id = 0x4DBB, .name = "Seek", .importance = .default, },
    ElementInfo { .id = 0x53AB, .name = "SeekID", .importance = .default, },
    ElementInfo { .id = 0x53AC, .name = "SeekPosition", .importance = .default, },
    ElementInfo { .id = 0x1549A966, .name = "Info", .importance = .important, },
    ElementInfo { .id = 0x73A4, .name = "SegmentUUID", .importance = .default, },
    ElementInfo { .id = 0x7384, .name = "SegmentFilename", .importance = .default, },
    ElementInfo { .id = 0x3CB923, .name = "PrevUUID", .importance = .default, },
    ElementInfo { .id = 0x3C83AB, .name = "PrevFilename", .importance = .default, },
    ElementInfo { .id = 0x3EB923, .name = "NextUUID", .importance = .default, },
    ElementInfo { .id = 0x3E83BB, .name = "NextFilename", .importance = .default, },
    ElementInfo { .id = 0x4444, .name = "SegmentFamily", .importance = .default, },
    ElementInfo { .id = 0x6924, .name = "ChapterTranslate", .importance = .default, },
    ElementInfo { .id = 0x69A5, .name = "ChapterTranslateID", .importance = .default, },
    ElementInfo { .id = 0x69BF, .name = "ChapterTranslateCodec", .importance = .default, },
    ElementInfo { .id = 0x69FC, .name = "ChapterTranslateEditionUID", .importance = .default, },
    ElementInfo { .id = 0x2AD7B1, .name = "TimestampScale", .importance = .important, },
    ElementInfo { .id = 0x4489, .name = "Duration", .importance = .default, },
    ElementInfo { .id = 0x4461, .name = "DateUTC", .importance = .default, },
    ElementInfo { .id = 0x7BA9, .name = "Title", .importance = .default, },
    ElementInfo { .id = 0x4D80, .name = "MuxingApp", .importance = .default, },
    ElementInfo { .id = 0x5741, .name = "WritingApp", .importance = .default, },
    ElementInfo { .id = 0x1F43B675, .name = "Cluster", .importance = .hot, },
    ElementInfo { .id = 0xE7, .name = "Timestamp", .importance = .hot, },
    ElementInfo { .id = 0x5854, .name = "SilentTracks", .importance = .default, },
    ElementInfo { .id = 0x58D7, .name = "SilentTrackNumber", .importance = .default, },
    ElementInfo { .id = 0xA7, .name = "Position", .importance = .default, },
    ElementInfo { .id = 0xAB, .name = "PrevSize", .importance = .default, },
    ElementInfo { .id = 0xA3, .name = "SimpleBlock", .importance = .hot, },
    ElementInfo { .id = 0xA0, .name = "BlockGroup", .importance = .important, },
    ElementInfo { .id = 0xA1, .name = "Block", .importance = .important, },
    ElementInfo { .id = 0xA2, .name = "BlockVirtual", .importance = .default, },
    ElementInfo { .id = 0x75A1, .name = "BlockAdditions", .importance = .default, },
    ElementInfo { .id = 0xA6, .name = "BlockMore", .importance = .default, },
    ElementInfo { .id = 0xA5, .name = "BlockAdditional", .importance = .default, },
    ElementInfo { .id = 0xEE, .name = "BlockAddID", .importance = .default, },
    ElementInfo { .id = 0x9B, .name = "BlockDuration", .importance = .important, },
    ElementInfo { .id = 0xFA, .name = "ReferencePriority", .importance = .default, },
    ElementInfo { .id = 0xFB, .name = "ReferenceBlock", .importance = .default, },
    ElementInfo { .id = 0xFD, .name = "ReferenceVirtual", .importance = .default, },
    ElementInfo { .id = 0xA4, .name = "CodecState", .importance = .default, },
    ElementInfo { .id = 0x75A2, .name = "DiscardPadding", .importance = .default, },
    ElementInfo { .id = 0x8E, .name = "Slices", .importance = .default, },
    ElementInfo { .id = 0xE8, .name = "TimeSlice", .importance = .default, },
    ElementInfo { .id = 0xCC, .name = "LaceNumber", .importance = .default, },
    ElementInfo { .id = 0xCD, .name = "FrameNumber", .importance = .default, },
    ElementInfo { .id = 0xCB, .name = "BlockAdditionID", .importance = .default, },
    ElementInfo { .id = 0xCE, .name = "Delay", .importance = .default, },
    ElementInfo { .id = 0xCF, .name = "SliceDuration", .importance = .default, },
    ElementInfo { .id = 0xC8, .name = "ReferenceFrame", .importance = .default, },
    ElementInfo { .id = 0xC9, .name = "ReferenceOffset", .importance = .default, },
    ElementInfo { .id = 0xCA, .name = "ReferenceTimestamp", .importance = .default, },
    ElementInfo { .id = 0xAF, .name = "EncryptedBlock", .importance = .default, },
    ElementInfo { .id = 0x1654AE6B, .name = "Tracks", .importance = .important, },
    ElementInfo { .id = 0xAE, .name = "TrackEntry", .importance = .important, },
    ElementInfo { .id = 0xD7, .name = "TrackNumber", .importance = .important, },
    ElementInfo { .id = 0x73C5, .name = "TrackUID", .importance = .default, },
    ElementInfo { .id = 0x83, .name = "TrackType", .importance = .important, },
    ElementInfo { .id = 0xB9, .name = "FlagEnabled", .importance = .default, },
    ElementInfo { .id = 0x88, .name = "FlagDefault", .importance = .default, },
    ElementInfo { .id = 0x55AA, .name = "FlagForced", .importance = .default, },
    ElementInfo { .id = 0x55AB, .name = "FlagHearingImpaired", .importance = .default, },
    ElementInfo { .id = 0x55AC, .name = "FlagVisualImpaired", .importance = .default, },
    ElementInfo { .id = 0x55AD, .name = "FlagTextDescriptions", .importance = .default, },
    ElementInfo { .id = 0x55AE, .name = "FlagOriginal", .importance = .default, },
    ElementInfo { .id = 0x55AF, .name = "FlagCommentary", .importance = .default, },
    ElementInfo { .id = 0x9C, .name = "FlagLacing", .importance = .default, },
    ElementInfo { .id = 0x6DE7, .name = "MinCache", .importance = .default, },
    ElementInfo { .id = 0x6DF8, .name = "MaxCache", .importance = .default, },
    ElementInfo { .id = 0x23E383, .name = "DefaultDuration", .importance = .default, },
    ElementInfo { .id = 0x234E7A, .name = "DefaultDecodedFieldDuration", .importance = .default, },
    ElementInfo { .id = 0x23314F, .name = "TrackTimestampScale", .importance = .default, },
    ElementInfo { .id = 0x537F, .name = "TrackOffset", .importance = .default, },
    ElementInfo { .id = 0x55EE, .name = "MaxBlockAdditionID", .importance = .default, },
    ElementInfo { .id = 0x41E4, .name = "BlockAdditionMapping", .importance = .default, },
    ElementInfo { .id = 0x41F0, .name = "BlockAddIDValue", .importance = .default, },
    ElementInfo { .id = 0x41A4, .name = "BlockAddIDName", .importance = .default, },
    ElementInfo { .id = 0x41E7, .name = "BlockAddIDType", .importance = .default, },
    ElementInfo { .id = 0x41ED, .name = "BlockAddIDExtraData", .importance = .default, },
    ElementInfo { .id = 0x536E, .name = "Name", .importance = .default, },
    ElementInfo { .id = 0x22B59C, .name = "Language", .importance = .default, },
    ElementInfo { .id = 0x22B59D, .name = "LanguageBCP47", .importance = .default, },
    ElementInfo { .id = 0x86, .name = "CodecID", .importance = .important, },
    ElementInfo { .id = 0x63A2, .name = "CodecPrivate", .importance = .important, },
    ElementInfo { .id = 0x258688, .name = "CodecName", .importance = .default, },
    ElementInfo { .id = 0x7446, .name = "AttachmentLink", .importance = .default, },
    ElementInfo { .id = 0x3A9697, .name = "CodecSettings", .importance = .default, },
    ElementInfo { .id = 0x3B4040, .name = "CodecInfoURL", .importance = .default, },
    ElementInfo { .id = 0x26B240, .name = "CodecDownloadURL", .importance = .default, },
    ElementInfo { .id = 0xAA, .name = "CodecDecodeAll", .importance = .default, },
    ElementInfo { .id = 0x6FAB, .name = "TrackOverlay", .importance = .default, },
    ElementInfo { .id = 0x56AA, .name = "CodecDelay", .importance = .default, },
    ElementInfo { .id = 0x56BB, .name = "SeekPreRoll", .importance = .default, },
    ElementInfo { .id = 0x6624, .name = "TrackTranslate", .importance = .default, },
    ElementInfo { .id = 0x66A5, .name = "TrackTranslateTrackID", .importance = .default, },
    ElementInfo { .id = 0x66BF, .name = "TrackTranslateCodec", .importance = .default, },
    ElementInfo { .id = 0x66FC, .name = "TrackTranslateEditionUID", .importance = .default, },
    ElementInfo { .id = 0xE0, .name = "Video", .importance = .important, },
    ElementInfo { .id = 0x9A, .name = "FlagInterlaced", .importance = .default, },
    ElementInfo { .id = 0x9D, .name = "FieldOrder", .importance = .default, },
    ElementInfo { .id = 0x53B8, .name = "StereoMode", .importance = .default, },
    ElementInfo { .id = 0x53C0, .name = "AlphaMode", .importance = .default, },
    ElementInfo { .id = 0x53B9, .name = "OldStereoMode", .importance = .default, },
    ElementInfo { .id = 0xB0, .name = "PixelWidth", .importance = .important, },
    ElementInfo { .id = 0xBA, .name = "PixelHeight", .importance = .important, },
    ElementInfo { .id = 0x54AA, .name = "PixelCropBottom", .importance = .default, },
    ElementInfo { .id = 0x54BB, .name = "PixelCropTop", .importance = .default, },
    ElementInfo { .id = 0x54CC, .name = "PixelCropLeft", .importance = .default, },
    ElementInfo { .id = 0x54DD, .name = "PixelCropRight", .importance = .default, },
    ElementInfo { .id = 0x54B0, .name = "DisplayWidth", .importance = .default, },
    ElementInfo { .id = 0x54BA, .name = "DisplayHeight", .importance = .default, },
    ElementInfo { .id = 0x54B2, .name = "DisplayUnit", .importance = .default, },
    ElementInfo { .id = 0x54B3, .name = "AspectRatioType", .importance = .default, },
    ElementInfo { .id = 0x2EB524, .name = "UncompressedFourCC", .importance = .default, },
    ElementInfo { .id = 0x2FB523, .name = "GammaValue", .importance = .default, },
    ElementInfo { .id = 0x2383E3, .name = "FrameRate", .importance = .default, },
    ElementInfo { .id = 0x55B0, .name = "Colour", .importance = .default, },
    ElementInfo { .id = 0x55B1, .name = "MatrixCoefficients", .importance = .default, },
    ElementInfo { .id = 0x55B2, .name = "BitsPerChannel", .importance = .default, },
    ElementInfo { .id = 0x55B3, .name = "ChromaSubsamplingHorz", .importance = .default, },
    ElementInfo { .id = 0x55B4, .name = "ChromaSubsamplingVert", .importance = .default, },
    ElementInfo { .id = 0x55B5, .name = "CbSubsamplingHorz", .importance = .default, },
    ElementInfo { .id = 0x55B6, .name = "CbSubsamplingVert", .importance = .default, },
    ElementInfo { .id = 0x55B7, .name = "ChromaSitingHorz", .importance = .default, },
    ElementInfo { .id = 0x55B8, .name = "ChromaSitingVert", .importance = .default, },
    ElementInfo { .id = 0x55B9, .name = "Range", .importance = .default, },
    ElementInfo { .id = 0x55BA, .name = "TransferCharacteristics", .importance = .default, },
    ElementInfo { .id = 0x55BB, .name = "Primaries", .importance = .default, },
    ElementInfo { .id = 0x55BC, .name = "MaxCLL", .importance = .default, },
    ElementInfo { .id = 0x55BD, .name = "MaxFALL", .importance = .default, },
    ElementInfo { .id = 0x55D0, .name = "MasteringMetadata", .importance = .default, },
    ElementInfo { .id = 0x55D1, .name = "PrimaryRChromaticityX", .importance = .default, },
    ElementInfo { .id = 0x55D2, .name = "PrimaryRChromaticityY", .importance = .default, },
    ElementInfo { .id = 0x55D3, .name = "PrimaryGChromaticityX", .importance = .default, },
    ElementInfo { .id = 0x55D4, .name = "PrimaryGChromaticityY", .importance = .default, },
    ElementInfo { .id = 0x55D5, .name = "PrimaryBChromaticityX", .importance = .default, },
    ElementInfo { .id = 0x55D6, .name = "PrimaryBChromaticityY", .importance = .default, },
    ElementInfo { .id = 0x55D7, .name = "WhitePointChromaticityX", .importance = .default, },
    ElementInfo { .id = 0x55D8, .name = "WhitePointChromaticityY", .importance = .default, },
    ElementInfo { .id = 0x55D9, .name = "LuminanceMax", .importance = .default, },
    ElementInfo { .id = 0x55DA, .name = "LuminanceMin", .importance = .default, },
    ElementInfo { .id = 0x7670, .name = "Projection", .importance = .default, },
    ElementInfo { .id = 0x7671, .name = "ProjectionType", .importance = .default, },
    ElementInfo { .id = 0x7672, .name = "ProjectionPrivate", .importance = .default, },
    ElementInfo { .id = 0x7673, .name = "ProjectionPoseYaw", .importance = .default, },
    ElementInfo { .id = 0x7674, .name = "ProjectionPosePitch", .importance = .default, },
    ElementInfo { .id = 0x7675, .name = "ProjectionPoseRoll", .importance = .default, },
    ElementInfo { .id = 0xE1, .name = "Audio", .importance = .important, },
    ElementInfo { .id = 0xB5, .name = "SamplingFrequency", .importance = .important, },
    ElementInfo { .id = 0x78B5, .name = "OutputSamplingFrequency", .importance = .default, },
    ElementInfo { .id = 0x9F, .name = "Channels", .importance = .important, },
    ElementInfo { .id = 0x7D7B, .name = "ChannelPositions", .importance = .default, },
    ElementInfo { .id = 0x6264, .name = "BitDepth", .importance = .default, },
    ElementInfo { .id = 0x52F1, .name = "Emphasis", .importance = .default, },
    ElementInfo { .id = 0xE2, .name = "TrackOperation", .importance = .default, },
    ElementInfo { .id = 0xE3, .name = "TrackCombinePlanes", .importance = .default, },
    ElementInfo { .id = 0xE4, .name = "TrackPlane", .importance = .default, },
    ElementInfo { .id = 0xE5, .name = "TrackPlaneUID", .importance = .default, },
    ElementInfo { .id = 0xE6, .name = "TrackPlaneType", .importance = .default, },
    ElementInfo { .id = 0xE9, .name = "TrackJoinBlocks", .importance = .default, },
    ElementInfo { .id = 0xED, .name = "TrackJoinUID", .importance = .default, },
    ElementInfo { .id = 0xC0, .name = "TrickTrackUID", .importance = .default, },
    ElementInfo { .id = 0xC1, .name = "TrickTrackSegmentUID", .importance = .default, },
    ElementInfo { .id = 0xC6, .name = "TrickTrackFlag", .importance = .default, },
    ElementInfo { .id = 0xC7, .name = "TrickMasterTrackUID", .importance = .default, },
    ElementInfo { .id = 0xC4, .name = "TrickMasterTrackSegmentUID", .importance = .default, },
    ElementInfo { .id = 0x6D80, .name = "ContentEncodings", .importance = .default, },
    ElementInfo { .id = 0x6240, .name = "ContentEncoding", .importance = .default, },
    ElementInfo { .id = 0x5031, .name = "ContentEncodingOrder", .importance = .default, },
    ElementInfo { .id = 0x5032, .name = "ContentEncodingScope", .importance = .default, },
    ElementInfo { .id = 0x5033, .name = "ContentEncodingType", .importance = .default, },
    ElementInfo { .id = 0x5034, .name = "ContentCompression", .importance = .important, },
    ElementInfo { .id = 0x4254, .name = "ContentCompAlgo", .importance = .default, },
    ElementInfo { .id = 0x4255, .name = "ContentCompSettings", .importance = .default, },
    ElementInfo { .id = 0x5035, .name = "ContentEncryption", .importance = .default, },
    ElementInfo { .id = 0x47E1, .name = "ContentEncAlgo", .importance = .default, },
    ElementInfo { .id = 0x47E2, .name = "ContentEncKeyID", .importance = .default, },
    ElementInfo { .id = 0x47E7, .name = "ContentEncAESSettings", .importance = .default, },
    ElementInfo { .id = 0x47E8, .name = "AESSettingsCipherMode", .importance = .default, },
    ElementInfo { .id = 0x47E3, .name = "ContentSignature", .importance = .default, },
    ElementInfo { .id = 0x47E4, .name = "ContentSigKeyID", .importance = .default, },
    ElementInfo { .id = 0x47E5, .name = "ContentSigAlgo", .importance = .default, },
    ElementInfo { .id = 0x47E6, .name = "ContentSigHashAlgo", .importance = .default, },
    ElementInfo { .id = 0x1C53BB6B, .name = "Cues", .importance = .default, },
    ElementInfo { .id = 0xBB, .name = "CuePoint", .importance = .default, },
    ElementInfo { .id = 0xB3, .name = "CueTime", .importance = .default, },
    ElementInfo { .id = 0xB7, .name = "CueTrackPositions", .importance = .default, },
    ElementInfo { .id = 0xF7, .name = "CueTrack", .importance = .default, },
    ElementInfo { .id = 0xF1, .name = "CueClusterPosition", .importance = .default, },
    ElementInfo { .id = 0xF0, .name = "CueRelativePosition", .importance = .default, },
    ElementInfo { .id = 0xB2, .name = "CueDuration", .importance = .default, },
    ElementInfo { .id = 0x5378, .name = "CueBlockNumber", .importance = .default, },
    ElementInfo { .id = 0xEA, .name = "CueCodecState", .importance = .default, },
    ElementInfo { .id = 0xDB, .name = "CueReference", .importance = .default, },
    ElementInfo { .id = 0x96, .name = "CueRefTime", .importance = .default, },
    ElementInfo { .id = 0x97, .name = "CueRefCluster", .importance = .default, },
    ElementInfo { .id = 0x535F, .name = "CueRefNumber", .importance = .default, },
    ElementInfo { .id = 0xEB, .name = "CueRefCodecState", .importance = .default, },
    ElementInfo { .id = 0x1941A469, .name = "Attachments", .importance = .default, },
    ElementInfo { .id = 0x61A7, .name = "AttachedFile", .importance = .default, },
    ElementInfo { .id = 0x467E, .name = "FileDescription", .importance = .default, },
    ElementInfo { .id = 0x466E, .name = "FileName", .importance = .default, },
    ElementInfo { .id = 0x4660, .name = "FileMediaType", .importance = .default, },
    ElementInfo { .id = 0x465C, .name = "FileData", .importance = .default, },
    ElementInfo { .id = 0x46AE, .name = "FileUID", .importance = .default, },
    ElementInfo { .id = 0x4675, .name = "FileReferral", .importance = .default, },
    ElementInfo { .id = 0x4661, .name = "FileUsedStartTime", .importance = .default, },
    ElementInfo { .id = 0x4662, .name = "FileUsedEndTime", .importance = .default, },
    ElementInfo { .id = 0x1043A770, .name = "Chapters", .importance = .default, },
    ElementInfo { .id = 0x45B9, .name = "EditionEntry", .importance = .default, },
    ElementInfo { .id = 0x45BC, .name = "EditionUID", .importance = .default, },
    ElementInfo { .id = 0x45BD, .name = "EditionFlagHidden", .importance = .default, },
    ElementInfo { .id = 0x45DB, .name = "EditionFlagDefault", .importance = .default, },
    ElementInfo { .id = 0x45DD, .name = "EditionFlagOrdered", .importance = .default, },
    ElementInfo { .id = 0x4520, .name = "EditionDisplay", .importance = .default, },
    ElementInfo { .id = 0x4521, .name = "EditionString", .importance = .default, },
    ElementInfo { .id = 0x45E4, .name = "EditionLanguageIETF", .importance = .default, },
    ElementInfo { .id = 0xB6, .name = "ChapterAtom", .importance = .default, },
    ElementInfo { .id = 0x73C4, .name = "ChapterUID", .importance = .default, },
    ElementInfo { .id = 0x5654, .name = "ChapterStringUID", .importance = .default, },
    ElementInfo { .id = 0x91, .name = "ChapterTimeStart", .importance = .default, },
    ElementInfo { .id = 0x92, .name = "ChapterTimeEnd", .importance = .default, },
    ElementInfo { .id = 0x98, .name = "ChapterFlagHidden", .importance = .default, },
    ElementInfo { .id = 0x4598, .name = "ChapterFlagEnabled", .importance = .default, },
    ElementInfo { .id = 0x6E67, .name = "ChapterSegmentUUID", .importance = .default, },
    ElementInfo { .id = 0x4588, .name = "ChapterSkipType", .importance = .default, },
    ElementInfo { .id = 0x6EBC, .name = "ChapterSegmentEditionUID", .importance = .default, },
    ElementInfo { .id = 0x63C3, .name = "ChapterPhysicalEquiv", .importance = .default, },
    ElementInfo { .id = 0x8F, .name = "ChapterTrack", .importance = .default, },
    ElementInfo { .id = 0x89, .name = "ChapterTrackUID", .importance = .default, },
    ElementInfo { .id = 0x80, .name = "ChapterDisplay", .importance = .default, },
    ElementInfo { .id = 0x85, .name = "ChapString", .importance = .default, },
    ElementInfo { .id = 0x437C, .name = "ChapLanguage", .importance = .default, },
    ElementInfo { .id = 0x437D, .name = "ChapLanguageBCP47", .importance = .default, },
    ElementInfo { .id = 0x437E, .name = "ChapCountry", .importance = .default, },
    ElementInfo { .id = 0x6944, .name = "ChapProcess", .importance = .default, },
    ElementInfo { .id = 0x6955, .name = "ChapProcessCodecID", .importance = .default, },
    ElementInfo { .id = 0x450D, .name = "ChapProcessPrivate", .importance = .default, },
    ElementInfo { .id = 0x6911, .name = "ChapProcessCommand", .importance = .default, },
    ElementInfo { .id = 0x6922, .name = "ChapProcessTime", .importance = .default, },
    ElementInfo { .id = 0x6933, .name = "ChapProcessData", .importance = .default, },
    ElementInfo { .id = 0x1254C367, .name = "Tags", .importance = .default, },
    ElementInfo { .id = 0x7373, .name = "Tag", .importance = .default, },
    ElementInfo { .id = 0x63C0, .name = "Targets", .importance = .default, },
    ElementInfo { .id = 0x68CA, .name = "TargetTypeValue", .importance = .default, },
    ElementInfo { .id = 0x63CA, .name = "TargetType", .importance = .default, },
    ElementInfo { .id = 0x63C5, .name = "TagTrackUID", .importance = .default, },
    ElementInfo { .id = 0x63C9, .name = "TagEditionUID", .importance = .default, },
    ElementInfo { .id = 0x63C4, .name = "TagChapterUID", .importance = .default, },
    ElementInfo { .id = 0x63C6, .name = "TagAttachmentUID", .importance = .default, },
    ElementInfo { .id = 0x67C8, .name = "SimpleTag", .importance = .default, },
    ElementInfo { .id = 0x45A3, .name = "TagName", .importance = .default, },
    ElementInfo { .id = 0x447A, .name = "TagLanguage", .importance = .default, },
    ElementInfo { .id = 0x447B, .name = "TagLanguageBCP47", .importance = .default, },
    ElementInfo { .id = 0x4484, .name = "TagDefault", .importance = .default, },
    ElementInfo { .id = 0x44B4, .name = "TagDefaultBogus", .importance = .default, },
    ElementInfo { .id = 0x4487, .name = "TagString", .importance = .default, },
    ElementInfo { .id = 0x4485, .name = "TagBinary", .importance = .default, },
};

pub const hot_elements = [_]IdInfo {
    IdInfo { .id = 0x1F43B675, .name = "Cluster" },
    IdInfo { .id = 0xE7, .name = "Timestamp" },
    IdInfo { .id = 0xA3, .name = "SimpleBlock" },
};

pub const important_elements = [_]IdInfo {
    IdInfo { .id = 0x18538067, .name = "Segment" },
    IdInfo { .id = 0x1549A966, .name = "Info" },
    IdInfo { .id = 0x2AD7B1, .name = "TimestampScale" },
    IdInfo { .id = 0xA0, .name = "BlockGroup" },
    IdInfo { .id = 0xA1, .name = "Block" },
    IdInfo { .id = 0x9B, .name = "BlockDuration" },
    IdInfo { .id = 0x1654AE6B, .name = "Tracks" },
    IdInfo { .id = 0xAE, .name = "TrackEntry" },
    IdInfo { .id = 0xD7, .name = "TrackNumber" },
    IdInfo { .id = 0x83, .name = "TrackType" },
    IdInfo { .id = 0x86, .name = "CodecID" },
    IdInfo { .id = 0x63A2, .name = "CodecPrivate" },
    IdInfo { .id = 0xE0, .name = "Video" },
    IdInfo { .id = 0xB0, .name = "PixelWidth" },
    IdInfo { .id = 0xBA, .name = "PixelHeight" },
    IdInfo { .id = 0xE1, .name = "Audio" },
    IdInfo { .id = 0xB5, .name = "SamplingFrequency" },
    IdInfo { .id = 0x9F, .name = "Channels" },
    IdInfo { .id = 0x5034, .name = "ContentCompression" },
};
